# Generated by Django 4.2 on 2023-04-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("img", models.ImageField(upload_to="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
