# Generated by Django 4.2 on 2023-04-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_part_options_part_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="part",
            name="img",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="part",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
    ]
